name: println
description: Dart println function, with variant argument.
version: 1.0.4
repository: https://github.com/yangentao/println
homepage: https://github.com/yangentao/println

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  #  any_call: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
